function test_bbm92_operation()
% TEST_BBM92_OPERATION
% Validate BBM92 operating-region classification.

    tolerance = 1e-12;

    Q_threshold = 0.11;

    %--------------------------------------------------------------
    % Both QBERs below threshold
    %--------------------------------------------------------------

    qber = struct();

    qber.Q_Z = 0.02;
    qber.Q_X = 0.08;

    classification = classify_bbm92_operation( ...
        qber, ...
        Q_threshold);

    assert( ...
        classification.is_operational, ...
        'test_bbm92_operation:OperationalState', ...
        'State below both QBER thresholds must be operational.');

    assert( ...
        abs(classification.Q_worst - 0.08) < tolerance, ...
        'test_bbm92_operation:WorstQBER', ...
        'Incorrect worst-basis QBER.');

    assert( ...
        abs(classification.margin_Z - 0.09) < tolerance, ...
        'test_bbm92_operation:MarginZ', ...
        'Incorrect Z-basis operating margin.');

    assert( ...
        abs(classification.margin_X - 0.03) < tolerance, ...
        'test_bbm92_operation:MarginX', ...
        'Incorrect X-basis operating margin.');

    assert( ...
        abs(classification.margin_worst - 0.03) < tolerance, ...
        'test_bbm92_operation:WorstMargin', ...
        'Incorrect worst-basis operating margin.');

    %--------------------------------------------------------------
    % Q_X above threshold
    %--------------------------------------------------------------

    qber.Q_Z = 0.02;
    qber.Q_X = 0.15;

    classification = classify_bbm92_operation( ...
        qber, ...
        Q_threshold);

    assert( ...
        ~classification.is_operational, ...
        'test_bbm92_operation:NonOperationalX', ...
        'State above the X-basis threshold must be non-operational.');

    assert( ...
        classification.margin_worst < 0, ...
        'test_bbm92_operation:NegativeMargin', ...
        'Non-operational state must have negative worst-basis margin.');

    %--------------------------------------------------------------
    % Q_Z above threshold
    %--------------------------------------------------------------

    qber.Q_Z = 0.14;
    qber.Q_X = 0.03;

    classification = classify_bbm92_operation( ...
        qber, ...
        Q_threshold);

    assert( ...
        ~classification.is_operational, ...
        'test_bbm92_operation:NonOperationalZ', ...
        'State above the Z-basis threshold must be non-operational.');

    %--------------------------------------------------------------
    % Exactly at threshold
    %
    % The adopted operating condition is Q < Q_threshold.
    %--------------------------------------------------------------

    qber.Q_Z = 0.05;
    qber.Q_X = Q_threshold;

    classification = classify_bbm92_operation( ...
        qber, ...
        Q_threshold);

    assert( ...
        ~classification.is_operational, ...
        'test_bbm92_operation:ThresholdEquality', ...
        'QBER equal to the threshold must be non-operational.');

    assert( ...
        abs(classification.margin_worst) < tolerance, ...
        'test_bbm92_operation:ZeroMargin', ...
        'State exactly at the boundary must have zero margin.');

    fprintf('test_bbm92_operation passed.\n');

end