function test_operating_boundary()
% TEST_OPERATING_BOUNDARY
% Validate extraction of operating-region boundaries from one-dimensional
% parameter sweeps.

    tolerance = 1e-12;

    %--------------------------------------------------------------
    % Single crossing
    %
    % metric = x
    % threshold = 0.5
    %
    % Exact crossing:
    % x = 0.5
    %--------------------------------------------------------------

    parameter_values = [0, 0.25, 0.75, 1.0];
    metric_values = parameter_values;

    threshold = 0.5;

    boundary = extract_operating_boundary( ...
        parameter_values, ...
        metric_values, ...
        threshold);

    assert( ...
        boundary.num_crossings == 1, ...
        'test_operating_boundary:SingleCrossingCount', ...
        'Expected exactly one threshold crossing.');

    assert( ...
        abs(boundary.first_crossing - 0.5) < tolerance, ...
        'test_operating_boundary:SingleCrossingValue', ...
        'Incorrect interpolated threshold crossing.');

    assert( ...
        abs(boundary.last_crossing - 0.5) < tolerance, ...
        'test_operating_boundary:SingleLastCrossing', ...
        'Incorrect last threshold crossing.');

    expected_mask = [true; true; false; false];

    assert( ...
        isequal(boundary.operating_mask, expected_mask), ...
        'test_operating_boundary:OperatingMask', ...
        'Incorrect operating-region mask.');

    %--------------------------------------------------------------
    % Multiple crossings
    %
    % Values alternate around threshold = 0.5.
    %
    % Expected crossings:
    % x = 0.5, 1.5, 2.5
    %--------------------------------------------------------------

    parameter_values = [0, 1, 2, 3];
    metric_values = [0, 1, 0, 1];

    threshold = 0.5;

    boundary = extract_operating_boundary( ...
        parameter_values, ...
        metric_values, ...
        threshold);

    expected_crossings = [0.5; 1.5; 2.5];

    assert( ...
        boundary.num_crossings == 3, ...
        'test_operating_boundary:MultipleCrossingCount', ...
        'Expected three threshold crossings.');

    assert( ...
        norm(boundary.crossing_values - expected_crossings) < tolerance, ...
        'test_operating_boundary:MultipleCrossingValues', ...
        'Incorrect multiple threshold crossings.');

    %--------------------------------------------------------------
    % No crossing: fully operational
    %--------------------------------------------------------------

    parameter_values = [0, 1, 2, 3];
    metric_values = [0.01, 0.02, 0.03, 0.04];

    threshold = 0.1;

    boundary = extract_operating_boundary( ...
        parameter_values, ...
        metric_values, ...
        threshold);

    assert( ...
        boundary.num_crossings == 0, ...
        'test_operating_boundary:NoCrossingOperational', ...
        'No threshold crossing should be detected.');

    assert( ...
        isnan(boundary.first_crossing), ...
        'test_operating_boundary:NoFirstCrossing', ...
        'First crossing must be NaN when no crossing exists.');

    assert( ...
        all(boundary.operating_mask), ...
        'test_operating_boundary:FullyOperational', ...
        'All points should be classified inside the operating region.');

    %--------------------------------------------------------------
    % No crossing: fully non-operational
    %--------------------------------------------------------------

    metric_values = [0.20, 0.25, 0.30, 0.35];

    boundary = extract_operating_boundary( ...
        parameter_values, ...
        metric_values, ...
        threshold);

    assert( ...
        boundary.num_crossings == 0, ...
        'test_operating_boundary:NoCrossingNonOperational', ...
        'No threshold crossing should be detected.');

    assert( ...
        ~any(boundary.operating_mask), ...
        'test_operating_boundary:FullyNonOperational', ...
        'All points should be outside the operating region.');

    %--------------------------------------------------------------
    % Exact grid-point crossing
    %--------------------------------------------------------------

    parameter_values = [0, 1, 2, 3];
    metric_values = [0.0, 0.5, 0.8, 1.0];

    threshold = 0.5;

    boundary = extract_operating_boundary( ...
        parameter_values, ...
        metric_values, ...
        threshold);

    assert( ...
        boundary.num_crossings == 1, ...
        'test_operating_boundary:ExactCrossingCount', ...
        'Expected one exact threshold crossing.');

    assert( ...
        abs(boundary.first_crossing - 1.0) < tolerance, ...
        'test_operating_boundary:ExactCrossingValue', ...
        'Incorrect exact threshold crossing.');

    fprintf('test_operating_boundary passed.\n');

end