clear;
clc;

% Adding tree structure to current path
addpath(genpath(pwd));

% ==========================================
% Experiment 1 - Baseline Phase Sweep
% ==========================================
run_experiment_1_phase_baseline_sweep();


% ==========================================
% Experiment 2 - Random Phase Ensemble State
% ==========================================
experiment_2_cases = {
    struct( ...
        'distribution_type', 'constant', ...
        'num_samples', 100, ...
        'parameters', { {pi/4} }, ...
        'label', 'constant: theta = pi/4' ...
    ), ...
    struct( ...
        'distribution_type', 'uniform', ...
        'num_samples', 100, ...
        'parameters', { {0, 2*pi} }, ...
        'label', 'uniform: [0, 2*pi]' ...
    ), ...
    struct( ...
        'distribution_type', 'gaussian', ...
        'num_samples', 100, ...
        'parameters', { {0, 1} }, ...
        'label', 'gaussian: mu = 0, sigma = 1' ...
    )
};

results_experiment_2_all = cell(1, numel(experiment_2_cases));

for case_idx = 1:numel(experiment_2_cases)

    current_case = experiment_2_cases{case_idx};

    fprintf('\n');
    fprintf('==========================================\n');
    fprintf('Experiment 2 - Case %d\n', case_idx);
    fprintf('Distribution: %s\n', current_case.label);
    fprintf('==========================================\n');

    theta_samples = generate_theta_samples( ...
        current_case.distribution_type, ...
        current_case.num_samples, ...
        current_case.parameters{:});

    results_experiment_2_all{case_idx} = run_experiment_2_random_phase(theta_samples);

end