% BLOCH_SPHERE_CONTRACTION_FIGURE
% Generate an illustrative Bloch-sphere figure for thesis visualization.
%
% Objective:
%   Display the geometrical meaning of pure and mixed single-qubit states
%   in the Bloch-sphere representation.
%
%   The figure shows:
%
%       1) pure Bloch vectors on the sphere surface, |r| = 1
%       2) mixed Bloch vectors inside the sphere, |r| < 1
%       3) radial contraction toward the maximally mixed state I/2
%
% Notes:
%   This script is only intended to generate a thesis figure.
%   It is not part of the simulator codebase.
%
%   A single-qubit pure state lies on the Bloch-sphere surface.
%   A single-qubit mixed state lies inside the Bloch sphere.
%
%   A contraction maps:
%
%       r -> alpha r,   0 <= alpha <= 1
%
%   and therefore moves Bloch vectors toward the origin.

clear;
close all;
clc;


% =========================
% Project paths
% =========================

output_folder = [ ...
    '/home/marcocioci/HPC/THESIS-Quantum-Communications/', ...
    'Quantum-Fiber-Simulator/images/theory'];

output_file = fullfile(output_folder, ...
    'bloch_sphere_vector_contraction.png');

if ~exist(output_folder, 'dir')
    mkdir(output_folder);
end


% =========================
% Plot style
% =========================

palette = get_plot_palette();
style   = get_plot_style();


% =========================
% Physical parameters
% =========================

contraction_factor = 0.55;

r_pure_1 = [0.55; 0.35; 0.76];
r_pure_1 = r_pure_1 / norm(r_pure_1);

r_pure_2 = [-0.60; 0.55; 0.58];
r_pure_2 = r_pure_2 / norm(r_pure_2);

r_mixed_1 = contraction_factor * r_pure_1;
r_mixed_2 = contraction_factor * r_pure_2;


% =========================
% Figure
% =========================

fig = figure( ...
    'Color', 'w', ...
    'Renderer', style.figure.renderer);

set(fig, ...
    'Units', 'pixels', ...
    'Position', [100, 100, 900, 720]);

ax = axes(fig);

hold(ax, 'on');
grid(ax, style.axes.grid);
box(ax, style.axes.box);
axis(ax, 'equal');

draw_bloch_sphere(ax, palette);
draw_cartesian_axes(ax, palette);

h_pure_1 = draw_bloch_vector(ax, r_pure_1, ...
    '$|\mathbf{r}_1|=1$', palette.blue, 2.6);

h_mixed_1 = draw_bloch_vector(ax, r_mixed_1, ...
    '', palette.orange, 2.6);

h_mixed_2 = draw_bloch_vector(ax, r_mixed_2, ...
    '', palette.red, 2.6);

h_pure_2 = draw_bloch_vector(ax, r_pure_2, ...
    '$|\mathbf{r}_2|=1$', palette.green, 2.6);

draw_norm_label(ax, r_mixed_1, ...
    '$|\mathbf{r}_1^\prime|<1$', palette.orange);

draw_norm_label(ax, r_mixed_2, ...
    '$|\mathbf{r}_2^\prime|<1$', palette.red);

h_center = plot3(ax, 0, 0, 0, 'o', ...
    'MarkerSize', 7, ...
    'MarkerFaceColor', palette.black, ...
    'MarkerEdgeColor', palette.black);

text(ax, 0.05, 0.05, 0.05, '$I/2$', ...
    'Interpreter', 'latex', ...
    'FontSize', 13, ...
    'FontWeight', 'bold', ...
    'Color', palette.black);


% =========================
% Labels and formatting
% =========================

title(ax, 'Bloch-Sphere Representation of State Contraction', ...
    'Interpreter', 'latex', ...
    'FontSize', style.title.font_size, ...
    'FontWeight', style.title.font_weight);

xlabel(ax, '$r_x$', ...
    'Interpreter', style.labels.interpreter, ...
    'FontSize', style.labels.font_size_axis);

ylabel(ax, '$r_y$', ...
    'Interpreter', style.labels.interpreter, ...
    'FontSize', style.labels.font_size_axis);

zlabel(ax, '$r_z$', ...
    'Interpreter', style.labels.interpreter, ...
    'FontSize', style.labels.font_size_axis);

xlim(ax, [-1.25, 1.25]);
ylim(ax, [-1.25, 1.25]);
zlim(ax, [-1.25, 1.25]);

pbaspect(ax, [1, 1, 1]);
daspect(ax, [1, 1, 1]);

set(ax, ...
    'FontSize', style.axes.font_size, ...
    'LineWidth', style.axes.line_width, ...
    'TickLabelInterpreter', style.axes.tick_label_interpreter, ...
    'Layer', style.axes.layer);

view(ax, 38, 24);

h_legend = legend(ax, ...
    [h_pure_1, h_mixed_1, ...
     h_pure_2, h_mixed_2, ...
     h_center], ...
    {'pure state 1', ...
     'contracted mixed state 1', ...
     'pure state 2', ...
     'contracted mixed state 2', ...
     'maximally mixed state $I/2$'}, ...
    'Location', 'southoutside', ...
    'Orientation', 'horizontal', ...
    'Interpreter', style.legend.interpreter, ...
    'FontSize', style.legend.font_size);

h_legend.Position(2) = h_legend.Position(2) - 0.035;


% =========================
% Export
% =========================

exportgraphics(fig, output_file, 'Resolution', 300);

fprintf('Saved Bloch-sphere contraction figure to:\n%s\n', output_file);


% ========================================================
% Local helper functions
% ========================================================

function draw_bloch_sphere(ax, palette)
% DRAW_BLOCH_SPHERE  Draw a transparent Bloch sphere.

    [X, Y, Z] = sphere(100);

    surf(ax, X, Y, Z, ...
        'FaceColor', palette.gray_light, ...
        'FaceAlpha', 0.08, ...
        'EdgeColor', palette.gray_mid, ...
        'EdgeAlpha', 0.12, ...
        'LineWidth', 0.3);

end


function draw_cartesian_axes(ax, palette)
% DRAW_CARTESIAN_AXES  Draw Bloch reference axes x, y, z.

    axis_limit = 1.15;

    plot3(ax, [-axis_limit, axis_limit], [0, 0], [0, 0], ':', ...
        'LineWidth', 1.0, ...
        'Color', palette.gray_dark);

    plot3(ax, [0, 0], [-axis_limit, axis_limit], [0, 0], ':', ...
        'LineWidth', 1.0, ...
        'Color', palette.gray_dark);

    plot3(ax, [0, 0], [0, 0], [-axis_limit, axis_limit], ':', ...
        'LineWidth', 1.0, ...
        'Color', palette.gray_dark);

    text(ax, 1.20, 0, 0, '$r_x$', ...
        'Interpreter', 'latex', ...
        'FontWeight', 'bold', ...
        'Color', palette.gray_dark);

    text(ax, 0, 1.20, 0, '$r_y$', ...
        'Interpreter', 'latex', ...
        'FontWeight', 'bold', ...
        'Color', palette.gray_dark);

    text(ax, 0, 0, 1.20, '$r_z$', ...
        'Interpreter', 'latex', ...
        'FontWeight', 'bold', ...
        'Color', palette.gray_dark);

end


function h_vector = draw_bloch_vector(ax, r_vector, label_text, color_value, line_width)
% DRAW_BLOCH_VECTOR  Draw one Bloch vector as an arrow.

    h_vector = quiver3(ax, 0, 0, 0, ...
        r_vector(1), r_vector(2), r_vector(3), ...
        0, ...
        'LineWidth', line_width, ...
        'Color', color_value, ...
        'MaxHeadSize', 0.35);

    plot3(ax, r_vector(1), r_vector(2), r_vector(3), 'o', ...
        'MarkerSize', 7, ...
        'MarkerFaceColor', color_value, ...
        'MarkerEdgeColor', color_value);

    if ~isempty(label_text)

        text(ax, ...
            1.12 * r_vector(1), ...
            1.12 * r_vector(2), ...
            1.12 * r_vector(3), ...
            label_text, ...
            'Interpreter', 'latex', ...
            'Color', color_value, ...
            'FontWeight', 'bold', ...
            'FontSize', 12);

    end

end


function draw_norm_label(ax, r_vector, label_text, color_value)
% DRAW_NORM_LABEL  Draw a compact label for a contracted Bloch-vector norm.

    label_position = 0.78 * r_vector;

    text(ax, ...
        label_position(1), ...
        label_position(2), ...
        label_position(3), ...
        label_text, ...
        'Interpreter', 'latex', ...
        'Color', color_value, ...
        'FontWeight', 'bold', ...
        'FontSize', 11);

end